### ISSUE TITLE
Auto promotes to queen.

### ISSUE THREAD

**Issue by andreyskv** [theborakompanioni/angular-chess#1]
Piece promotion needs to have an option other than queen to comply with chess rules. Probably using a built in spare pieces bar could be a solution.

**Comment by theborakompanioni** [comment]
@andreyskv Thank you for your reports. I will hopefully have some time in coming weeks and will fix it as soon as possible.

**Comment by andreyskv** [comment]
Thanks. I am playing around here and just implemented selecting promotion piece overlay, but pretty much all the changes are actually in the chessboard.js and only some part is in the angular-chess in the onDrop function to detect it is promotion. I am not sure how to contribute this code because changes are in 2 different javascript libs. Anyway I can send you patches if interested.

**Comment by theborakompanioni** [comment]
@andreyskv Definitely interested. As you can see this repo has not been given much love to recently. I am eager to implement a better api and improve usability. Can you provide your goals?

**Comment by theborakompanioni** [comment]
Closing as this can be archived by defining custom angular-chessboard callbacks.
