### ISSUE TITLE
chessboardjs OnChange event is not supported...

### ISSUE THREAD

**Issue by andreyskv** [theborakompanioni/angular-chess#2]
There is a bunch of callbacks possible to assign to the angular-chessboard, but angular-chess wraps around and isolates them. It is probably true that most of  drag/mouse events do not need to be exposed in the actual chess implementation, but the OnChange event is really important to be able to assign a callback.

**Comment by andreyskv** [comment]
So what I did for now is this. I changed Onchage in the newtonChessgame directive. I simply assign  onBoardChanged in my controller. Not proper "angular" solution though.

if ($scope.$parent.onBoardChanged){
return $scope.$parent.onBoardChanged(oldPosition, newPosition);
}
return angular.noop(oldPosition, newPosition);

**Comment by theborakompanioni** [comment]
Thanks @andreyskv . I hope I will have time in the near future to work on angular-chess again. I do not want to make any time estimations on when that will be. Nevertheless, I am open to pull requests, so if you have a proper solution - keep em' coming!

**Comment by theborakompanioni** [comment]
Closing as this is a non-issue for angular-chess. `onChange` callback is supported in [angular-chessboard](https://github.com/theborakompanioni/angular-chessboard).
