### ISSUE TITLE
What about tap behavior instead of drag n drop

### ISSUE THREAD

**Issue by irongomme** [theborakompanioni/angular-chess#3]
It would be nice to have this behavior : 
- User tap / click the piece he wants to move
- Only squares allowed highlights
- User tap / click the destination square

Is there a simple way to implement this kind of behavior ?

**Comment by theborakompanioni** [comment]
Take a look at the docs of [chessboard.js](https://github.com/oakmac/chessboardjs) and the following example [Highlight Legal Moves](http://chessboardjs.com/examples#5003). angular-chessboard should be able to be configured to do this. 

Maybe  [chessboardjs#85](https://github.com/oakmac/chessboardjs/issues/85) can guide you in right direction or watch if someone on [chessboardjs#110](https://github.com/oakmac/chessboardjs/issues/110) provides a solution that suits your needs.

**Comment by theborakompanioni** [comment]
Closing this as it will not be implemented in the near future.
